R2EMU_DIR = $(shell pwd)
SCRIPTS = $(R2EMU_DIR)/scripts
TOOLS = $(R2EMU_DIR)/tools
export R2EMU_HOME=$(abspath $(R2EMU_DIR))

ifeq ($(wildcard $(R2EMU_HOME)/src/main.rs),)
	$(error R2EMU_HOME=$(R2EMU_HOME) is not a R2EMU_HOME repo)
endif

# Tools Func def
remove_quote = $(patsubst "%",%,$(1))

# first before include config/auto.conf
all: build

# Kconfig
KCONFIG_CONFIG  = $(R2EMU_HOME)/.config
KCONFIG_FILE    = $(R2EMU_HOME)/Kconfig
KCONFIG_INC_DIR = $(R2EMU_HOME)/include
KCONFIG_SRC_DIR = $(TOOLS)/kconfig
KCONFIG_CONF    = $(KCONFIG_SRC_DIR)/build/conf
KCONFIG_MCONF   = $(KCONFIG_SRC_DIR)/build/mconf

KCONFIG_INC_GEN_DIR    = $(KCONFIG_INC_DIR)/generated
KCONFIG_INC_CONFIG_DIR = $(KCONFIG_INC_DIR)/config
KCONFIG_AUTOCONF_H     = $(KCONFIG_INC_GEN_DIR)/autoconf.h
KCONFIG_AUTO_CONF      = $(KCONFIG_INC_CONFIG_DIR)/auto.conf

export KCONFIG_CONFIG
export KCONFIG_AUTOHEADER = $(KCONFIG_AUTOCONF_H)

ifeq ($(filter clean distclean, $(MAKECMDGOALS)),)
	# Include variables and rules generated by menuconfig
	-include $(KCONFIG_INC_CONFIG_DIR)/auto.conf
	-include $(KCONFIG_INC_CONFIG_DIR)/auto.conf.cmd
	GUEST_ISA ?= $(call remove_quote,$(CONFIG_GUEST_ISA))

	# difftest
	-include $(TOOLS)/difftest.mk
endif

$(KCONFIG_MCONF):
	$(MAKE) -C $(KCONFIG_SRC_DIR) NAME=mconf

$(KCONFIG_CONF):
	$(MAKE) -C $(KCONFIG_SRC_DIR)

# .config 规则
$(KCONFIG_CONFIG): $(KCONFIG_MCONF) $(KCONFIG_FILE) $(KCONFIG_CONF)
	@if [ ! -f .config ]; then \
		echo ">>> .config not found. Running interactive menuconfig for initial configuration."; \
		$(KCONFIG_MCONF) $(KCONFIG_FILE) \
	else \
		echo ">>> .config found. Checking for updates with oldconfig."; \
		$(KCONFIG_CONF) --oldconfig $(KCONFIG_FILE); \
	fi

$(KCONFIG_AUTOCONF_H) $(KCONFIG_AUTO_CONF): $(KCONFIG_CONFIG) $(KCONFIG_CONF)
	@echo ">>>.config updated. Generating autoconf.h..."
	@$(KCONFIG_CONF) --syncconfig $(KCONFIG_FILE)

build: $(KCONFIG_CONFIG) $(KCONFIG_AUTOCONF_H) $(DIFF_REF_SO)
	@cargo build

build-release: $(KCONFIG_CONFIG) $(KCONFIG_AUTOCONF_H) $(DIFF_REF_SO)
	@cargo build --release

run: build
	cargo run

clean:
	@echo CARGO CLEAN
	@cargo clean

distclean:
	@cargo clean
	@rm -f .config
	@rm -f .config.old
	@rm -rf $(KCONFIG_INC_DIR)
	$(MAKE) -C $(KCONFIG_SRC_DIR) clean
	$(MAKE) -C $(TOOLS)/spike-diff clean

menuconfig: $(KCONFIG_MCONF) $(KCONFIG_CONF)
	$(KCONFIG_MCONF) $(KCONFIG_FILE)
	@echo ">>>.config updated. Generating autoconf.h..."
	@$(KCONFIG_CONF) --syncconfig $(KCONFIG_FILE)

.PHONY: menuconfig build run clean distclean build-release
